/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/old/AppFooter.vue')['default']
    Cookie_settings: typeof import('./components/onboard/sign_up/terms_popups/cookie_settings.vue')['default']
    Create_password: typeof import('./components/onboard/sign_up/sign_up_steps/create_password.vue')['default']
    CustomVideo: typeof import('./components/common/CustomVideo.vue')['default']
    DialogChapterList: typeof import('./components/class/regular/DialogChapterList.vue')['default']
    DialogDownload: typeof import('./components/class/regular/DialogDownload.vue')['default']
    DialogLessonList: typeof import('./components/class/regular/DialogLessonList.vue')['default']
    ExpressionSentenceList: typeof import('./components/class/regular/ExpressionSentenceList.vue')['default']
    ExpressionWordList: typeof import('./components/class/regular/ExpressionWordList.vue')['default']
    Find_account: typeof import('./components/onboard/log_in/find/find_account.vue')['default']
    Find_account_result: typeof import('./components/onboard/log_in/find/find_account_result.vue')['default']
    HelloWorld: typeof import('./components/old/HelloWorld.vue')['default']
    LandingCarousels: typeof import('./components/onboard/landing/LandingCarousels.vue')['default']
    LectureList: typeof import('./components/class/lecture/LectureList.vue')['default']
    LectureMain: typeof import('./components/class/lecture/LectureMain.vue')['default']
    LessonList: typeof import('./components/class/regular/LessonList.vue')['default']
    Level_test_step_0: typeof import('./components/onboard/sign_up/level_test_steps/level_test_step_0.vue')['default']
    Level_test_step_results: typeof import('./components/onboard/sign_up/level_test_steps/level_test_step_results.vue')['default']
    Log_in_by_email: typeof import('./components/onboard/log_in/email/log_in_by_email.vue')['default']
    Pick_username: typeof import('./components/onboard/sign_up/sign_up_steps/pick_username.vue')['default']
    ProgressBar: typeof import('./components/common/ProgressBar.vue')['default']
    RegularMain: typeof import('./components/class/regular/RegularMain.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select_country: typeof import('./components/onboard/sign_up/sign_up_steps/select_country.vue')['default']
    ShortFormMain: typeof import('./components/class/short_form/ShortFormMain.vue')['default']
    Survey_skip: typeof import('./components/onboard/sign_up/survey_steps/survey_skip.vue')['default']
    Survey_step_0: typeof import('./components/onboard/sign_up/survey_steps/survey_step_0.vue')['default']
    Survey_step_1: typeof import('./components/onboard/sign_up/survey_steps/survey_step_1.vue')['default']
    Survey_step_2: typeof import('./components/onboard/sign_up/survey_steps/survey_step_2.vue')['default']
    Survey_step_3: typeof import('./components/onboard/sign_up/survey_steps/survey_step_3.vue')['default']
    Survey_step_4: typeof import('./components/onboard/sign_up/survey_steps/survey_step_4.vue')['default']
    TextDevider: typeof import('./components/common/TextDevider.vue')['default']
    Verify_email: typeof import('./components/onboard/sign_up/sign_up_steps/verify_email.vue')['default']
    Verify_phone: typeof import('./components/onboard/sign_up/sign_up_steps/verify_phone.vue')['default']
  }
}
